#!/bin/bash
#
# NHSO Revenue Intelligence - Quick Install Script
# Version: 3.1.0
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/aegisx-platform/eclaim-rep-download/main/install.sh | bash
#
# Options:
#   --mysql    Use MySQL instead of PostgreSQL
#   --no-db    Download-only mode (no database)
#   --dir      Installation directory (default: nhso-revenue)
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Default values
VERSION="latest"
INSTALL_DIR="nhso-revenue"
DB_TYPE="postgresql"
GITHUB_RAW="https://raw.githubusercontent.com/aegisx-platform/eclaim-rep-download/main"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --mysql)    DB_TYPE="mysql"; shift ;;
        --no-db)    DB_TYPE="none"; shift ;;
        --dir)      INSTALL_DIR="$2"; shift 2 ;;
        --version)  VERSION="$2"; shift 2 ;;
        -h|--help)
            echo "NHSO Revenue Intelligence Installer"
            echo ""
            echo "Usage: curl -fsSL https://raw.githubusercontent.com/aegisx-platform/eclaim-rep-download/main/install.sh | bash -s -- [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --mysql      Use MySQL instead of PostgreSQL"
            echo "  --no-db      Download-only mode (no database)"
            echo "  --dir NAME   Installation directory (default: nhso-revenue)"
            echo "  --version V  Docker image version (default: latest)"
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║        NHSO Revenue Intelligence - Quick Install          ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check Docker
echo -e "${YELLOW}[1/5] Checking requirements...${NC}"
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed${NC}"
    echo "Please install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi
echo -e "${GREEN}✓ Docker found${NC}"

# Create directory
echo -e "${YELLOW}[2/5] Creating installation directory...${NC}"
if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}Warning: Directory '$INSTALL_DIR' already exists${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    [[ ! $REPLY =~ ^[Yy]$ ]] && echo "Cancelled" && exit 1
fi

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
echo -e "${GREEN}✓ Created: $(pwd)${NC}"

# Download docker-compose
echo -e "${YELLOW}[3/5] Downloading configuration...${NC}"

case $DB_TYPE in
    postgresql) COMPOSE_FILE="docker-compose-deploy.yml" ;;
    mysql)      COMPOSE_FILE="docker-compose-deploy-mysql.yml" ;;
    none)       COMPOSE_FILE="docker-compose-deploy-no-db.yml" ;;
esac

curl -fsSL "${GITHUB_RAW}/${COMPOSE_FILE}" -o docker-compose.yml
echo -e "${GREEN}✓ Downloaded docker-compose.yml (${DB_TYPE})${NC}"

# Create directories
mkdir -p downloads/{rep,stm,smt} logs config
echo -e "${GREEN}✓ Created directories${NC}"

# Create .env
echo -e "${YELLOW}[4/5] Configuring credentials...${NC}"
echo ""
echo -e "${BLUE}กรุณาใส่ข้อมูลเข้าสู่ระบบ E-Claim:${NC}"
echo ""

read -p "ECLAIM_USERNAME: " ECLAIM_USER
read -s -p "ECLAIM_PASSWORD: " ECLAIM_PASS
echo ""

cat > .env << EOF
# NHSO Revenue Intelligence
# Generated by install.sh

# E-Claim Credentials
ECLAIM_USERNAME=${ECLAIM_USER}
ECLAIM_PASSWORD=${ECLAIM_PASS}

# Docker Image Version
VERSION=${VERSION}

# Web Port (change if 5001 is in use)
WEB_PORT=5001
EOF

echo -e "${GREEN}✓ Created .env${NC}"

# Start services
echo -e "${YELLOW}[5/5] Starting services...${NC}"
echo ""

if docker compose version &> /dev/null 2>&1; then
    docker compose pull
    docker compose up -d
else
    docker-compose pull
    docker-compose up -d
fi

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Installation Complete!                       ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "🌐 เข้าใช้งาน: ${BLUE}http://localhost:5001${NC}"
echo ""
echo -e "Commands:"
echo -e "  ${YELLOW}cd $(pwd)${NC}"
echo -e "  ${YELLOW}docker compose logs -f web${NC}    # ดู logs"
echo -e "  ${YELLOW}docker compose down${NC}           # หยุด"
echo -e "  ${YELLOW}docker compose up -d${NC}          # เริ่ม"
echo ""
echo -e "📚 Docs: ${BLUE}https://github.com/aegisx-platform/eclaim-rep-download${NC}"
echo ""
